name: build

on:
  push:
    branches:
      - "master"
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Clone ijkplayer-android
        run: |
          git clone https://github.com/Bilibili/ijkplayer.git ijkplayer-android
          cd ijkplayer-android
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r12b
      - name: Check NDK path
        run: |
          echo ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Set up yasm
        run: |
          wget http://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz
          tar -xvf yasm-1.3.0.tar.gz
          cd ./yasm-1.3.0
          ./configure
          make
          sudo make install
          cd ..
      - name: Build ijkplayer
        run: |
          export ANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }}
          cd ijkplayer-android
          ./init-android.sh
          ./init-android-openssl.sh
          echo 'export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=ac3"' >> ./config/module-lite.sh
          cd ./android/contrib
          ./compile-openssl.sh clean
          ./compile-openssl.sh all
          ./compile-ffmpeg.sh clean
          ./compile-ffmpeg.sh all
          cd ..
          ./compile-ijk.sh all
      - name: Clean objs
        run: |
          find . -type d -name "obj" | xargs rm -rf
      - name: ZIP ijkplayer
        run: |
          ls
          cd ijkplayer-android
          cd android
          zip -r ijkplayer.zip ./ijkplayer/
      - name: Upload ZIP
        uses: actions/upload-artifact@v1
        with:
          name: ijkplayer
          path: ./ijkplayer-android/android/ijkplayer.zip
